### ISSUE TITLE
Version bounds on Hackage are too strict

### ISSUE THREAD

**Issue by sternenseemann** [smallhadroncollider/taskell#100]
When building this with up to date dependencies you'll encounter the following issue:

```
aeson >=1.4.7.1 && <1.5,
base >=4.13.0.0 && <4.14,
brick >=0.52.1 && <0.53,
lens >=4.18.1 && <4.19,
tasty >=1.2.3 && <1.3,
tasty-expected-failure >=0.11.1.2 && <0.12,
template-haskell >=2.15.0.0 && <2.16,
vty >=5.28.2 && <5.29
```

These bounds are all to strict as taskell also compiles with the more up to date versions of these packages (i. e. all bounds removed).

**Comment by smallhadroncollider** [comment]
They're automatically added by Stack, so don't think I've got much control over it. I think I can set it to not add upper-bounds, but then there's no guarantee it would work.

**Comment by sternenseemann** [comment]
Could you combine multiple stack solvers to generate the bounds? I. e. lower from lts and upper from stackage nightly? Nightly would already help my use case actually.

**Comment by smallhadroncollider** [comment]
It looks like the `-revision` feature might handle this?

https://docs.haskellstack.org/en/stable/yaml_configuration/#pvp-bounds

I've never looked too much into the Cabal/Hackage side of things to be honest, so bit over my head.

**Comment by sternenseemann** [comment]
But they are PVP bounds already, cutting of at the next release that is considered breaking. The point is really that this is still too strict as all the breakages introduced by further releases don't affect taskell.

**Comment by smallhadroncollider** [comment]
That's a good point. I'll update it for the next release.

**Comment by smallhadroncollider** [comment]
Hadn't uploaded `1.11.0` to Hackage anyway, so that's up now without upper bounds. Let me know if that's any good.

**Comment by sternenseemann** [comment]
Great, that works, too.
