### ISSUE TITLE
binding to move to top of last list

### ISSUE THREAD

**Issue by ALMerrill** [smallhadroncollider/taskell#102]
In my workflow, it makes more sense to move an item to the top of the last list when I complete it. Is this something that is already possible or that could be added? I like being able to easily see the tasks I recently completed at the top of the Done list

**Comment by smallhadroncollider** [comment]
Adding this as an option would take a while, as I'd need to add support for a new binding and various other bits and bobs. All very doable, but I'm not sure when I'm going to be able to get back to woking on Taskell issues, so I can't guarantee I'd get around to it soon.

If you were prepared to do your own build then it would just be a matter of changing [this line](https://github.com/smallhadroncollider/taskell/blob/master/src/Taskell/Events/State.hs#L257):

```diff
-        else moveHorizontal (idx - cur) Lists.Bottom state
+        else moveHorizontal (idx - cur) Lists.Top state
```

**Comment by smallhadroncollider** [comment]
This has been added by @AliNisarAhmed. Will be in the next release.

**Comment by smallhadroncollider** [comment]
See https://github.com/smallhadroncollider/taskell/releases/tag/1.11.1
