### ISSUE TITLE
Invalid byte sequence error

### ISSUE THREAD

**Issue by helcone** [smallhadroncollider/taskell#114]
I compiled taskell and I also installed from a package manager and I received on both the same error when running the application 

``
taskell: /home/user/.config/taskell/config.ini: hGetContents: invalid argument (invalid byte sequence)
``
I access the config to find for any weird character o something like it but I am unable to find anything. 

I also found that this might have to do with utf but I do not know really how to fix this

Edit

I found that this error has to do with the LANG environment variable a quick fix might be to add `export LANG=en_US.UTF8 cabal build` to your bashrc but I recommend to check your /etc/locale.gen file and the run sudo locale-gen and this fixed the issue

**Comment by chenrui333** [comment]
I have tried the `export LANG=en_US.UTF8` route, unfortunately it does not work for my homebrew build, https://github.com/Homebrew/homebrew-core/pull/156130

in test, https://github.com/Homebrew/homebrew-core/actions/runs/7063961683/job/19231145142
or in build, https://github.com/Homebrew/homebrew-core/actions/runs/7064404195/job/19232491915?pr=156130
