### ISSUE TITLE
libtinfo.so.5: no version information available

### ISSUE THREAD

**Issue by jameh** [smallhadroncollider/taskell#12]
I'm trying to run the binary I downloaded from your release page for linux x64 (version 1.2.6) on Arch Linux, but when I run the binary, it first complains about a missing shared library file `libtinfo.so.5`. 

This file isn't in any of the official repo packages, but from my googling, I think it used to be provided by the `ncurses` package until it was upgraded to ncurses 6 or something like that.

People who ran into this problem [elsewhere](https://github.com/commercialhaskell/stack/issues/1012) suggested either symlinking to `libtinfo.so.6` or `libncursesw.so.6` from `libtinfo.so.5`, or to install `ncurses5-compat-libs` from the AUR user repo. Both of these approaches make taskell complain the following:

```
taskell: /usr/lib/libtinfo.so.5: no version information available (required by taskell)
taskell: /home/jamie/.taskell/config.ini: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by jameh** [comment]
I built from source using `stack`, which fixed the `no version information available` error.

The other error was fixed by setting my locale to `en_US.UTF-8`.

**Comment by smallhadroncollider** [comment]
Is the `ncurses` package different from the `ncurses-compat-libs` package? I'm told that the second one makes things work on Fedora, but I can't say I've tested it myself.

**Comment by smallhadroncollider** [comment]
Glad you got it working though!

**Comment by jameh** [comment]
The [`ncurses`](https://www.archlinux.org/packages/core/x86_64/ncurses) package is at version 6.1 at the time of writing, and hence doesn't supply the `libtinfo.so.5` link. The AUR package [`ncurses5-compat-libs`](https://aur.archlinux.org/packages/ncurses5-compat-libs) does provide it.

Building from source with the [`stack`](https://www.archlinux.org/packages/community/x86_64/stack) package seems to work without the need for the AUR package, or creating a symlink from `libtinfo.so.5`:

```
ls /usr/lib | grep libtinfo
libtinfo.so
libtinfo.so.6
```

```
pacman -Q | grep ncurses
ncurses 6.1-3
```

I'm excited to start using this for organizational things! thanks for making it
