### ISSUE TITLE
Is it possible to support Github Project board?

### ISSUE THREAD

**Issue by JimmyLv** [smallhadroncollider/taskell#13]

**Comment by smallhadroncollider** [comment]
It looks like it is supported via the GitHub API, but it's in developer preview, so it's subject to change: https://developer.github.com/v3/projects/columns/

Having said that, it should be fairly simple to get it working, so I'll have a look and see.

**Comment by smallhadroncollider** [comment]
I've got the basic version of this working now. Just need to make it accessible from the command line. Hopefully might get it out by the end of the day.

**Comment by smallhadroncollider** [comment]
This is in as of 1.3.0

Getting a project ID is not easy - you have to use the GitHub API. I plan on adding the ability for taskell to automatically fetch project IDs based on an organisation/repo. But not in yet.
