### ISSUE TITLE
Comments, multi-line descriptions, (non-TODO) lists

### ISSUE THREAD

**Issue by MatthiasKauer** [smallhadroncollider/taskell#14]
Hi,
New guy here, playing around with your program.

I just downloaded a board from my Trello account. 
The download worked fine. I then closed and re-opened Taskell and I ran into several issues:
```
$ taskell trello.md 
trello.md: could not parse line(s) 31, 65, 70, 72, 74, 75, 77, 78, 79, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 109, 110, 111, 115, 116, 117, 118, 119, 124, 125, 126, 128, 129, ....
```

My quick investigation makes it seem like there are the following issues:
- All multi-line descriptions cannot be read back in. In my case, some of these contain sublists, links, etc. 
- All commens are lost.

I don't see a way to manually add comments, multiline descriptions or lists in description. In fact, the current underlying Markdown format doesn't seem to support that, does it?

FWIW, I don't really need comments in a single-user system if I had multiline descriptions and/or sublists. I hope this isn't out of scope.

**Comment by MatthiasKauer** [comment]
As an example, consider the task which was downloaded as follows:
```
- Figure out XYZ situation
    @ 2017-12-03
    > Futher info:

- http://mywebsite.com/sublist
- OneNote
```
A cleaner format might be:
```
- Figure out XYZ situation
    @ 2017-12-03
    > Futher info:
        - http://mywebsite.com/sublist
        - OneNote
```
or with additional `>`
```
- Figure out XYZ situation
    @ 2017-12-03
    > Futher info:
    >    - http://mywebsite.com/sublist
    >    - OneNote
```
I tried the version below, actually, but Taskell currently only shows the last `>` as far as I can tell.
Anyway, I'm wondering what you think. Have you run into that issue before?

**Comment by smallhadroncollider** [comment]
You're right: multi-line descriptions aren't supported, but quite possible for Trello to have them. I think all the Trello boards I tested with had very simple test descriptions.

I will need to think about the format. I think the multiline `>` is probably the best option and should be relatively easy to add.

I'll then need to think about how you add a multiline description in Taskell itself. I guess maybe `Esc` to finish and `Enter` for return. Or possibly `Shift+Enter` (ala. Slack) for a new line.

**Comment by smallhadroncollider** [comment]
I've added support for this now. It will be in 1.3.0.

**Comment by MatthiasKauer** [comment]
Cool. I'm looking forward to trying it out.

**Comment by sanj0** [comment]
> You're right: multi-line descriptions aren't supported, but quite possible for Trello to have them. I think all the Trello boards I tested with had very simple test descriptions.
> 
> I will need to think about the format. I think the multiline `>` is probably the best option and should be relatively easy to add.
> 
> I'll then need to think about how you add a multiline description in Taskell itself. I guess maybe `Esc` to finish and `Enter` for return. Or possibly `Shift+Enter` (ala. Slack) for a new line.

Hey there! Late to the party but did the feature for multi-line input description ever happen? I'm stuck trying to figure out how it works -- typing `Enter` or `Shift+Enter` jumps to sub-tasks. I'm using 1.11.4 on arch.
