### ISSUE TITLE
libtinfo.so.5: no version information available

### ISSUE THREAD

**Issue by Ingvar33** [smallhadroncollider/taskell#17]
After running taskell I get a message
```
$ taskell -v
taskell: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by taskell)
1.3.2
```
Use Linux Mint 17.3

**Comment by smallhadroncollider** [comment]
You might need to install `ncurses-compat-libs`? Not sure if that'll do it to be honest and I'm on parental leave at the moment, so won't have time to look into it for a while if not.

Alternatively you could follow the instructions to build it yourself - but that's fairly time consuming.

**Comment by smallhadroncollider** [comment]
Did the above help? I'm going to close this issue for now - feel free to reopen it if you're still having issues.
