### ISSUE TITLE
Show warning/error when config is not correcty parsable

### ISSUE THREAD

**Issue by malteneuss** [smallhadroncollider/taskell#19]
I changed the coloring in theme.ini and used a color word that weren't specified. Even though only a single color word was wrong, the config file was ignored enteirely. Thus i was wondering why the default color scheme was still active untill i noticed my mistake. If possible, please report when a config is not parsable.

**Comment by smallhadroncollider** [comment]
Yes, definitely need to have better error messaging for config file issues.

I'm on parental leave for the next few months, but I'll look into this once I'm back.

**Comment by smallhadroncollider** [comment]
The `theme.ini` file is not parsed by the `taskell` code - it's part of the Brick framework which `taskell` is built on top of. So I'll need to see if Brick has a way of reporting errors for this. If it doesn't then I'll file an issue over on Brick.

**Comment by smallhadroncollider** [comment]
I think the theme code was some of the earliest stuff I wrote. Turns out I just ignore the errors that Brick generates! So should be fairly simple to get this working.

**Comment by smallhadroncollider** [comment]
This is fixed in [1.3.3](https://github.com/smallhadroncollider/taskell/releases/tag/1.3.3)
