### ISSUE TITLE
Pressing 'o' or 'O' while empty list/column is selected gets the cursor stuck

### ISSUE THREAD

**Issue by alex-dr** [smallhadroncollider/taskell#2]
![image](https://user-images.githubusercontent.com/8420104/34851203-fb0b2a52-f6f6-11e7-9f7b-9996dbc6d262.png)

Steps to reproduce: move to an empty column and press `o` or `O`. Your cursor is now trapped in the title with no way to escape or move or do anything.

Workarounds: `killall taskell` :(

**Comment by smallhadroncollider** [comment]
Good spot. Fixed a similar issue with `e` on Wednesday, but `o` uses much the same code so not surprising it breaks in the same way.

**Comment by smallhadroncollider** [comment]
Actually, that only fixed it for `O`. Let's give that another go...
