### ISSUE TITLE
400 error, cannot fetch file from Trello

### ISSUE THREAD

**Issue by ohayondotio** [smallhadroncollider/taskell#21]
I've added my token to the config.ini file and labeled it appropriately. When using the command `taskell -t BOARDNAME FILENAME.md`, I get an error 400 saying the file can not be fetched from Trello.

**Comment by smallhadroncollider** [comment]
Are you using the board *id*? 

(Sorry, on parental leave at the moment, so I might not respond quickly)

**Comment by ohayondotio** [comment]
Sorry, I'm a fool and was using the board name without realizing the board ID is the portion in the URL. Thank you and congratulations.
