### ISSUE TITLE
Cursor misplace with CJK characters

### ISSUE THREAD

**Issue by jiegec** [smallhadroncollider/taskell#23]
When typing CJK characters in taskell, for example:
![image](https://user-images.githubusercontent.com/6127678/49489482-297a7f00-f886-11e8-9a53-69e35586737b.png)
Where in fact the cursor is at the end of the text.

Cause: CJK characters are two-character wide.

**Comment by smallhadroncollider** [comment]
Thanks for reporting this one - not something I'd have ever spotted! I thought my code was taking character-width into account, but obviously something's not quite right.

**Comment by jiegec** [comment]
One possible reason I have observed in other programs could be that CJK characters account for three UTF-8 chars but have two chars' width.

**Comment by smallhadroncollider** [comment]
Really sorry, I can't believe this has been up for almost a year. Time flies when you have a kid!

Looking into this. Looks like my text cursor code sometimes uses `textWidth` (which takes UTF-8 widths into account) and sometimes uses `length` (which does not). Hopefully making it consistent will sort the issue.
