### ISSUE TITLE
Stack build fail

### ISSUE THREAD

**Issue by cvoges12** [smallhadroncollider/taskell#24]
Missing `zlib-0.6.2`
[Logs](https://0x0.st/shHk.log)
Why is this dependency not covered during `stack build`?

**Comment by smallhadroncollider** [comment]
Looks like it's an underlying dependency of one of the Haskell modules. Stack only fetches the Haskell modules themselves. If you install `zlib-devel` it should work.

See: https://github.com/haskell/zlib/issues/13

**Comment by cvoges12** [comment]
Ah, I see that it is a C library.
