### ISSUE TITLE
Nixos package

### ISSUE THREAD

**Issue by cvoges12** [smallhadroncollider/taskell#25]
Option for a nixpkg. This is probably more of an enhancement but it would make sure that dependencies such as a `zlib` are installed. I could write one.

**Comment by smallhadroncollider** [comment]
I'd like to support Nix, but it's not something I've used myself, so have no idea where to start. If you'd like to write one that would be great!

**Comment by cvoges12** [comment]
```
nix:
  enable: true
  packages: [ zlib ]
```

This will have to be added to the `stack.yaml` if I wish to use [stack to build the nix expression](https://nixos.org/nixpkgs/manual/#how-to-build-a-haskell-project-using-stack). Is this fine?

**Comment by smallhadroncollider** [comment]
Those docs say:

> If you want stack to *use Nix by default*, you can add a nix section to the stack.yaml file

I'm happy to support Nix, but I don't want it to be the default way to run it.

Can you build the nix expression and then remove those lines again? (I don't know what a "nix expression" is)

**Comment by smallhadroncollider** [comment]
I think this is supported now: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/misc/taskell

**Comment by cvoges12** [comment]
Awesome!
