### ISSUE TITLE
Help screen unreadable when arrows are used to move.

### ISSUE THREAD

**Issue by czarnoff** [smallhadroncollider/taskell#30]
I set my bindings so that the arrow keys and vim keys navigate the board.  When I go to the help screen, the movement key bindings dominate the help display and the explanation is 4 characters wide.

If the key bindings wrapped like the explanation, I think it would solve the issue.  
I'm using 1.4.1. If I figure out a solution before you do, I'll sent you a pull request.

**Comment by smallhadroncollider** [comment]
Will look into wrapping it. Alternatively I could maybe get it to display ↑ ↓ ← → instead.

**Comment by smallhadroncollider** [comment]
I've used the arrow icons for now. I need to rewrite the modal code at some point to support scrolling and smaller screens, so I'll do proper wrapping at that point.
