### ISSUE TITLE
libtinfo5 has to be installed manually on Ubuntu 18.10 for taskell to work

### ISSUE THREAD

**Issue by grzkv** [smallhadroncollider/taskell#31]
Running `taskell` fails on **Ubuntu 18.10**:
```
taskell: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

The `libtinfo5` libs are missing. After installing with:
```
sudo apt install libtinfo5
```
everything installs fine.

This happens when `taskell` is installed from `.deb` package.

**Comment by smallhadroncollider** [comment]
Thanks for that. I'll update the readme.
