### ISSUE TITLE
yes/no prompt should highlight the default

### ISSUE THREAD

**Issue by matthiasbeyer** [smallhadroncollider/taskell#32]
taskell asks whether to create a file when it does not exist.

Simply hitting enter defaults to "no".

The prompt for that is currently

```
Create /home/user/file.md? (y/n): 
```

but it should be

```
Create /home/user/file.md? (y/N): 
```

(Uppercase "N" because No is the default).

**Comment by smallhadroncollider** [comment]
This is on `develop` now and will be in the next release.

**Comment by smallhadroncollider** [comment]
Thanks!
