### ISSUE TITLE
Allow sub tasks reordering

### ISSUE THREAD

**Issue by shadowphoenixpt** [smallhadroncollider/taskell#34]
Would be possible to allow sub tasks to move up or down with K and J?

**Comment by smallhadroncollider** [comment]
One of my "do soon" tasks is to get the sub-task lists to use the same logic as the normal tasks list. Should avoid repetition but also mean that sub-tasks have all the same controls as regular tasks (where it makes sense to do so).

**Comment by smallhadroncollider** [comment]
Sorry it's been a while. Turns out young children get sick a lot and then can't go to nursery!

**Comment by smallhadroncollider** [comment]
Added in [1.7.1](https://github.com/smallhadroncollider/taskell/releases/tag/1.7.1)
