### ISSUE TITLE
taskell 1.4.2 fails loading config

### ISSUE THREAD

**Issue by matthiasbeyer** [smallhadroncollider/taskell#36]
See here: https://github.com/NixOS/nixpkgs/pull/60363#issuecomment-488576459

I updated taskell in nixpkgs and saw this error.

**Comment by matthiasbeyer** [comment]
Fun thing... also happens for 1.4.0 ... or am I am doing something wrong?

**Comment by smallhadroncollider** [comment]
Hmm, likely something to do with UTF-8 encoding of the files, but unclear why. I can't reproduce it on my machine.

**Comment by matthiasbeyer** [comment]
Maybe it is just a problem with my build environment. I will investigate this in the next few days (as I have time) and report back. Thanks for your patience!

**Comment by smallhadroncollider** [comment]
Ok, I'll close it for now. Feel free to re-open if you think it's something that needs further attention.
