### ISSUE TITLE
[search] case insensitive and whole text

### ISSUE THREAD

**Issue by cinghiopinghio** [smallhadroncollider/taskell#39]
Hi,
I'm new to Taskell, I'm testing if it fits my needs. Thanks for your effort.
I find the whole implementation is really well though, unfortunately for many entries the ability to filter out things becomes very useful. I find the actual behaviour of the search can be improved if:

- One can have case insensitive searches
- One can search the whole text (even descriptions), in this way one can fake a tag system with sth like `+tag` in the description
- One can select/edit an entry/task when a search is activated (atm when pressing enter or any keybinding to edit such task, nothing happens).

**Comment by smallhadroncollider** [comment]
All good points.

- Case-insensitive search would definitely be good - I had an issue with that this morning!
- Being able to search more generally would be useful - I actually thought I'd done this already
- You *should* be able to edit descriptions and such, but I think there's a bug which stops it

**Comment by cinghiopinghio** [comment]
Thanks, I'm happy you agree.
Unfortunately my knowledge of `Haskell` is zero, I can't be that helpful....

**Comment by smallhadroncollider** [comment]
The "not being able to do anything while in search mode" bug crept in when I added custom key bindings. It's basically ignoring any key bindings, so the only actions that work in search mode are pressing the number keys to change columns (as those are not affected by key bindings).

**Comment by smallhadroncollider** [comment]
Ok, I've got key bindings working with search again. But there's a bigger bug in the way that search works which means that completely the wrong task will come up if you press enter!

I need to rethink how search works.

**Comment by smallhadroncollider** [comment]
Getting there now. I've changed how searching is done under the hood, which simplifies the key binding logic massively. Now just fixing the various bugs regarding moving around in search.

**Comment by smallhadroncollider** [comment]
See [1.5.0](https://github.com/smallhadroncollider/taskell/releases/tag/1.5.0)
