### ISSUE TITLE
Move binary to top-level folder

### ISSUE THREAD

**Issue by tsoernes** [smallhadroncollider/taskell#4]
In the binary archive releases, the binary is way down in the folder structure in `.stack_work`. The top-level folder, starting with `.`, is hidden by default on some systems. It might be a good idea to move the binary to the top level.

**Comment by smallhadroncollider** [comment]
Ah, sorry about that, don't think I checked it since I switched over to using gzip.

**Comment by smallhadroncollider** [comment]
Sorted for the latest release and all future releases.
