### ISSUE TITLE
Creating a --- item in a list freezes program in 'INSERT MODE'

### ISSUE THREAD

**Issue by cvlvxi** [smallhadroncollider/taskell#42]
When I add an Item in a list and by default it being '---' it stays in INSERT mode and escape does not get out of INSERT mode and it just hangs

![Screen Shot 2019-08-08 at 2 39 12 pm](https://user-images.githubusercontent.com/41276358/62675472-84064500-b9ea-11e9-9f0f-93ce45e691af.png)

**Comment by smallhadroncollider** [comment]
Thanks for that. I'll have a look into it today.

**Comment by smallhadroncollider** [comment]
Looks like it's still accepting input - which is why none of the other keys work. Odd that `Esc` doesn't do anything. But shouldn't still be in insert mode anyway.

**Comment by smallhadroncollider** [comment]
Looks like this was caused by my checking if the index was *greater than* the length of the array instead of greater than *or equal to* 🤦‍♂

**Comment by smallhadroncollider** [comment]
Fixed in [1.5.1](https://github.com/smallhadroncollider/taskell/releases/tag/1.5.1)
