### ISSUE TITLE
Release tarball confusing

### ISSUE THREAD

**Issue by toonn** [smallhadroncollider/taskell#43]
Hi, I just noticed that the release tarballs have the taskell binary hidden away in `.stack-build/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/a68937786f5a8d27a9c4d37fb3903177309aa3a38822a2d481b66f2baed0c984/8.6.5/bin/`.
That's not very user friendly and it makes it look like the tarball is broken in some way because the hidden directory that's extracted is usually hidden from view and you're expecting a directory named something like `taskell-1.6.1`.

**Comment by smallhadroncollider** [comment]
Gah, sorry. That's an old issue that I fixed, but had to rewrite the build script a few weeks back as Stack changed the build directories. Clearly it's snuck back in.

**Comment by smallhadroncollider** [comment]
Should be sorted now. Thanks for alerting me to it 👍
