### ISSUE TITLE
In the DUE entry, i'd love to be able to put `1d` or `1w` etc...

### ISSUE THREAD

**Issue by joemaro** [smallhadroncollider/taskell#47]
Just like what i can do with `sleep 1h 15m`.

**Comment by tazimmerman** [comment]
Maybe this should be a separate issue, but it would also be nice to have the **Due** line display an input mask to remind the user what inputs are valid. I missed a dash between month and day, moved along with the rest of my edits, and only when I was back at the main screen did I realize the date hadn't changed. That said, if this goes against the ethos of the project, I can understand why you may want to avoid it.

That said, congrats on building a very cool & productive tool.

**Comment by smallhadroncollider** [comment]
@joemaro It's a nice idea. I'll add it to my list.

@tazimmerman Could you add that as a separate issue? Definitely some sort of date validation would be helpful - I also have that issue.

**Comment by smallhadroncollider** [comment]
I've got the basics of this working now, but it made me reevaluate how I was storing dates, which led to a big refactor. Think I've got the hardest bit done now, but not quite enough time to finish this off and test everything properly.

**Comment by smallhadroncollider** [comment]
This will be in 1.8.0

**Comment by joemaro** [comment]
You did it!!! I'm impressed and thankful! :) Merry Christmas to you!

**Comment by smallhadroncollider** [comment]
I've started using this feature so much since I added it. So thanks for suggesting!

Probably needs to not include the time for days and weeks.

**Comment by joemaro** [comment]
I'm sorry, but i don't understand what exactly your saying.

Maybe you mean that for cases where one puts in `4d` for example, taskell shouldn't display the resulting time, only the due date. Yes, i think that would the common way to do it... I don't need there to be a time when it's due in 3 days. I'd be fine with dates alone really, but i'm sure that some people prefer to be able to set precise times. Maybe a setting in the config file that switches between `date` and `date+time`? Not sure really... 
But yea, the simplest would be your idea of not displaying the time when one enters `1d` or `1w`.

**Comment by smallhadroncollider** [comment]
It supports `s` for seconds and `m` for minutes and `h` for hours. Most people are unlikely to use those, but they are there just in case. So I think it should add a time for those. But I think for longer term dates (days, weeks) then just default to the day without a time.
