### ISSUE TITLE
Validate the format of the Due date field

### ISSUE THREAD

**Issue by tazimmerman** [smallhadroncollider/taskell#49]
It would be nice to have the **Due** line display an input mask to remind the user what inputs are valid, or at the very least, reject changes that don't match a well known format (e.g. ISO 8601) with some kind of visible error. I missed a dash between month and day, moved along with the rest of my edits, and only when I was back at the main screen did I realize the date hadn't changed.

**Comment by smallhadroncollider** [comment]
This will be in 1.8.0

It won't let you finish inputting a date unless it's valid. I've also added time support.
