### ISSUE TITLE
Feature request: Use Github checkbox styling in MarkDown

### ISSUE THREAD

**Issue by jwillem** [smallhadroncollider/taskell#5]
Often I find it very useful to build a sublist of an bulletpoint, while I'm sketching ideas.
But there is no such feature, to display an sub-level of the markdown; or to rather simply create an body in taskell to a taskname.

**Comment by smallhadroncollider** [comment]
I'd like to get sublists working. It's on the roadmap.

**Comment by jwillem** [comment]
🌈🌈🌈
Great times.

**Comment by smallhadroncollider** [comment]
Added in `0.11.0`

**Comment by smallhadroncollider** [comment]
If using a file you wrote by hand you'll need to use `-` for top level lists and `*` for sub-lists

**Comment by smallhadroncollider** [comment]
On the `develop` branch I've added the ability to configure how the Markdown should be formatted, so you could set it to be something like:

```
## List Title

### Task
- Sub Task
- Sub Task
```

Or any other format you can think of

**Comment by jwillem** [comment]
Very nice, I've tested it just now.

As recommended I've used these params:
```
[markdown]
title = "##"
; each task is a header
task = "###"
; subtasks are list items under the header
subtask = "-"
```

The following Issues occur:
- Creating a brand new taskell-file with header and subtasks works, everything seems fine.
  - After reopening it, my titles have a double-hash prepended. (see img below)
  - manually changing it back brings no effect
- I like the "Subtask-Page"
  - what about tasks in subtasks? (just kidding ;P)
  - how do subtasks get completed? (I infer this by the count [0/3])
  - empty subtasks are possible and get counted

![image](https://user-images.githubusercontent.com/8223764/36905278-43ddca56-1e33-11e8-954d-1efbac5098fa.png)

Huge thanks for developing this piece of software!

**Comment by smallhadroncollider** [comment]
I’ll have a look into this when I’m back at work next week

**Comment by smallhadroncollider** [comment]
Ah, I see what's going on. The parsing code for titles just strips 1 character from the beginning - not taking the formatting into account.

**Comment by jwillem** [comment]
Yes, thank you. I've built it in 11min via brew. Any Idea why these builds take so relatively long?

Another thing:
- While you made the string configurable for a subitem, conf-items for a 'yet to be done' and complete subtask is not present yet. ;) See screenshot.
  - I would love to be github compatible with using a "- [ ]"(with space) and a "- [x]".

### task
  - [x] foo
  - [ ] bar


![image](https://user-images.githubusercontent.com/8223764/37170299-c2a694a4-230a-11e8-9c60-5c7f3b1fd7e2.png)

**Comment by smallhadroncollider** [comment]
11 minutes is quite quick! It takes about 20 on my machine. Haskell builds from scratch tend to be very slow: it has to download all the libraries, compile all of them, and then compile the app itself. It's the libraries that take all the time. I don't think they are available pre-compiled. I try to produce a pre-compiled version of the app for the last two versions of macOS, but it takes a while. I should look into automating it.

I'll look into adding different completion styles - didn't realise there was the checkbox format.

**Comment by smallhadroncollider** [comment]
I've switched over to use the Github style checklists by default now. I don't imagine anyone will miss the strike-through styling, so I've not added an option to switch back.

It will still read files using `~`, but they'll be converted to `[x]` when they are saved. I'll probably entirely remove support for `~` at some point in the future.

**Comment by smallhadroncollider** [comment]
See [1.2.4](https://github.com/smallhadroncollider/taskell/releases/tag/1.2.4)

I'm not doing Homebrew builds for point releases as it's very time consuming, so you'll need to download the binary and copy it into the relevant directory.

I'm trying to get taskell added to the official `homebrew-core` package, which automates the build process, but I'm not allowed to submit that myself, so hopefully I can find someone to volunteer to do that for me at some point.

**Comment by jwillem** [comment]
You are the bee's knees! I've compiled the now previous latest version just yesterday evening. XDThe "checkboxes" in subtasks look really good.I've seen you implemented an import of a trello duedate. Have you considered to integrate this (and a simple timetracking) besides the trello integration?Have a nice day!On 24 May 2018 10:21, Mark Wales <notifications@github.com> wrote:See 1.2.4
I'm not doing Homebrew builds for point releases as it's very time consuming, so you'll need to download the binary and copy it into the relevant directory.
I'm trying to get taskell added to the official homebrew-core package, which automates the build process, but I'm not allowed to submit that myself, so hopefully I can find someone to volunteer to do that for me at some point.

**Comment by smallhadroncollider** [comment]
The time-tracking stuff works without Trello too. If you press `@` you can now add a due date to any task. It will highlight in different colours depending on how soon it's due.
