### ISSUE TITLE
"Redo" feature would be good

### ISSUE THREAD

**Issue by joemaro** [smallhadroncollider/taskell#51]
just noticed that i'm so used to be able to do that, i think i don't know any programs that don't have it. Not *that* important though imo...

**Comment by smallhadroncollider** [comment]
It's on [the list](https://github.com/smallhadroncollider/taskell/blob/master/roadmap.md). Shouldn't be too hard to implement.

**Comment by smallhadroncollider** [comment]
Think I've got this working now, but I feel like redo is one of those things with weird edge cases that you need to be careful about, so going to write some more tests before doing a release.

**Comment by smallhadroncollider** [comment]
In [1.7.2](https://github.com/smallhadroncollider/taskell/releases/tag/1.7.2)
