### ISSUE TITLE
It's been 14 days and counting and 1.7.0 is still unavailable in Brew

### ISSUE THREAD

**Issue by macgeekpro** [smallhadroncollider/taskell#52]
Hi all! Anyone knows why it's taking 2 weeks for the latest build to make it over to Brew, which is still hosting v1.6.1?

BR,
Yoha

**Comment by smallhadroncollider** [comment]
Couple of reasons:

1) Someone else started doing the homebrew pull requests, which meant I lost control of the process.
2) There seems to be a build issue on the homebrew tests - not sure quite what's going on, seems to work on Travis, which is the same setup. Needs investigation.

Not ideal, but you can download the binary: https://github.com/smallhadroncollider/taskell/releases/download/1.7.2/taskell-1.7.2_x86-64-mac.tar.gz

**Comment by smallhadroncollider** [comment]
Looks like the build process doesn't have fixed package versions and for some reason the homebrew one is using a slightly newer version of a package, which seems to have introduced an error.

**Comment by smallhadroncollider** [comment]
Not the package that I thought it was causing the issue...

I use Stack to build taskell on my machine, which guarantees package consistency. Unfortunately homebrew doesn't support this and uses Cabal, which just uses the latest versions of packages.

I'm running a Cabal build on my machine at the moment to see what happens.

**Comment by smallhadroncollider** [comment]
Ok, I've fixed the package incompatibilities. Hopefully be up and merged into Homebrew later today.

**Comment by smallhadroncollider** [comment]
Latest version should be on Homebrew now

**Comment by macgeekpro** [comment]
@smallhadroncollider Thanks Mark for rectifying the issue and sharing the updates. I look forward to installing the latest build from brew.

**Comment by macgeekpro** [comment]
Fyi, the latest build is now live in brew. 🙏🏼
