### ISSUE TITLE
Statusbar toggle, adjustable top padding, move actions to top of lists

### ISSUE THREAD

**Issue by kaiec** [smallhadroncollider/taskell#54]
Hi Mark,

first of all: thank you for Taskell, I was in a hurry to find a tool for a very specific purpose and Taskell did the job almost perfect. I just needed some adjustments and did them in my fork very quick and dirty (I have no clue whatsoever about Haskell):

https://github.com/kaiec/taskell/commit/63417ea20de3227705d98474d0608a031fb6ed1f

My use case is a progress tracking during a programming screen cast. The terminal window with Taskell is visible almost the whole time with a small height and shows a Kanban Board where you see mainly the current task in the middle column, the most probable (planned) next task in the left column and the most recently finished task in the right  (done) column. To achieve this, I simply had to prepend tasks to the lists instead of appending, when I move a task. I actually like this behavior better anyway, as I usually deal with tasks at the top of the lists and when I move a task one column and then back, it ends up at the end of the list, instead of the old position at the top.

Anyhow, as this is for a screen cast, screen estate is extremely valuable and scarce, so I got rid of the status bar and set the top and bottom padding to 0. That's it, now I am happy. 

I assume, it would be super easy for you to add these changes to Taskell and of course make them configurable. If you want, I can also open a pull request, but I would definitely need help to get the additional code for the configuration and the tests right (I actually just deactivated the tests that I broke with my changes ;-)). 

Cheers,

Kai

**Comment by smallhadroncollider** [comment]
I can see that these would all be useful configuration options.

(Good job on editing the code if you've never done Haskell before - very tidy!)

**Comment by smallhadroncollider** [comment]
Moving to top of list could potentially just be a different key binding

**Comment by smallhadroncollider** [comment]
Padding and status bar config options will be in the next release. I might have time to get the moving to top of list stuff working tomorrow.

**Comment by smallhadroncollider** [comment]
[1.9.1](https://github.com/smallhadroncollider/taskell/releases/tag/1.9.1)

**Comment by smallhadroncollider** [comment]
I've added key bindings to move items to the top of a list. I'd suggest something like this in your `bindings.ini`:

```ini
moveLeftTop = H
moveRightTop = L
moveLeftBottom = ˙
moveRightBottom = ¬
```

The `...Bottom` ones are `alt+h` and `alt+l` on a Mac (currently they need to be set to something).

You'll want to get rid of `moveLeft` and `moveRight` - those are now just aliases for `moveLeftBottom` and `moveRightBottom`
