### ISSUE TITLE
The default "bindings.ini" is seen as invalid.

### ISSUE THREAD

**Issue by RuiRojo** [smallhadroncollider/taskell#56]
Without any "bindings.ini", in "~/.config/taskell", one is created automatically and I get the message "bindings.ini: invalid mapping - using default bindings".

I installed Taskell with `slack` on Fedora 31 with a non-standard keyboard layout (workman), so the first thing was to try to remap the movement keys. However, all I get is the default bindings because I can't get it to be seen as valid.

**Comment by smallhadroncollider** [comment]
Looks like when I added "redo" I forgot to add a corresponding binding. Need to rework the binding code as it's all over the place at the moment. If it was all in one place it wouldn't be possible for this to sneak in.

For now I'll just add the missing binding, which should sort the issue.

**Comment by smallhadroncollider** [comment]
Fixed in [1.7.4](https://github.com/smallhadroncollider/taskell/releases/tag/1.7.4)
