### ISSUE TITLE
Allow theming sub-tasks

### ISSUE THREAD

**Issue by rybak** [smallhadroncollider/taskell#58]
At the moment, sub-tasks are colored as following:

1. If sub-task is under cursor, use `taskCurrent`, else:
2. If sub-task is not done, use `titleCurrent`, else:
3. use default (sub-task is done).

It would be nice, if one could theme the done sub-tasks, for example, to a dimmer color.

**Comment by smallhadroncollider** [comment]
This seems sensible.

**Comment by smallhadroncollider** [comment]
This will be in the next release
