### ISSUE TITLE
Support 'gg' key combination as opposite of G

### ISSUE THREAD

**Issue by jelly** [smallhadroncollider/taskell#59]
It would be nice to have 'gg' as a support as it's the opposite of 'G' or is this complicated since it requires catching two keys?

**Comment by smallhadroncollider** [comment]
Catching two keys isn't currently supported, but I do need to rethink how the keybinding stuff works, so when I do that I could think about how to support more than a single key.

**Comment by jelly** [comment]
I've written this small patch to support 'g' as key combination as opposite of G. I'm however not sure if you like it or if it's written well enough.

https://pkgbuild.com/~jelle/taskell.patch

**Comment by smallhadroncollider** [comment]
Looks good. Do you want to do it as a pull request (into `develop`)?
