### ISSUE TITLE
Utf8? / Problem with display of char-set

### ISSUE THREAD

**Issue by jwillem** [smallhadroncollider/taskell#6]
![image](https://user-images.githubusercontent.com/8223764/35286949-948bcbe6-0061-11e8-84d6-7a03c0e6d942.png)
I'm using German punctuation, a so called "umlaut".
Taskell has an issue with the display of `Ü`

**Comment by smallhadroncollider** [comment]
Sorry about that. Don't think I've tried any non-ascii characters.

**Comment by jwillem** [comment]
You are welcome. ;)

**Comment by smallhadroncollider** [comment]
I think I've tracked this down to the Markdown parser - I'm using `ByteString`'s `pack` and `unpack` functions, which are not UTF-8 safe.

I'm going to use this as a chance to update all my `String`s to `Text` and then I can use `Text`'s `pack` and `unpack`. Should help me with some other issues too.

**Comment by smallhadroncollider** [comment]
Ok, fixed in the latest version. Just need to finish some layout code and then I'll get it up.
