### ISSUE TITLE
Controls Window should be scrollable or display "more"

### ISSUE THREAD

**Issue by joemaro** [smallhadroncollider/taskell#60]
I was searching for the hotkey to delete a list, which i had forgotten at that moment, and because my terminal font is so big that the `?` window can't list everything (and just won't display what doesn't fit). So there should be something like `[Space] ... more ...` which is what other programs usually do.

Happy new year and all the best to you and your family!

**Comment by smallhadroncollider** [comment]
Agreed. This is a long-standing issue that needs sorting for most the modal windows.

**Comment by smallhadroncollider** [comment]
Fixed in latest release thanks to @AliNisarAhmed
