### ISSUE TITLE
[GitHub] "Could not parse response" if there are github issues in the board

### ISSUE THREAD

**Issue by Psykopear** [smallhadroncollider/taskell#62]
Same as #20 

I can't import projects from private repositories.

Import of public projects works fine, but it gives an error if a try it with a private project, both with my personal account and with projects from an organization I'm in.

```
Import project: 1
Fetching project from GitHub...
Could not parse response. Please file an Issue on GitHub:
https://github.com/smallhadroncollider/taskell/issues/new


Error in $[1].note: parsing Text failed, expected String, but encountered Null
```

I'm not familiar with haskell so I can't really help with code, but let me know if I can give you more info to debug the problem.

**Comment by smallhadroncollider** [comment]
That's a very useful additional bit of information. Haven't ever tried it with private repos - sort of assumed they'd be the same!

Looks like one of the expected fields isn't present on the private repo.

**Comment by smallhadroncollider** [comment]
Hmm, just tried it on a private project of mine and it worked.

**Comment by smallhadroncollider** [comment]
Maybe I need to add a dump of what it's trying to parse (or a `verbose` option to do this), otherwise it's going to be hard to workout what's going on.

**Comment by Psykopear** [comment]
Let me know when and how I can run the patched version and I'll send you the output.
If it worked on one of your private repos, I'll try to see if I can make it work too (trying with a clean repository, or adding tabs notes and issues to see if there is something that makes it work) so we might get closer to the solution.

**Comment by smallhadroncollider** [comment]
Looking at the error again, it looks like it's something to do with getting a `null` note. Which is just the text of a card. But I can't add a card without any text when I try.

Are you using the "automated tasks" stuff for any of them?

**Comment by Psykopear** [comment]
Yes, I'm using "automated tasks" and I use "issues" in the board rather than notes, so if the assumption is that the board contains notes rather than issues this might be the problem.

**Comment by smallhadroncollider** [comment]
Yup, it's the issues that are causing the issues.

**Comment by smallhadroncollider** [comment]
Ok, I've had a look at the JSON. Looks like "Issues" have `null` for their `notes` property.

Looks like it provides another end-point I can fetch to get the content of the issue. Will have a look into that - otherwise it would just have to be blank, which isn't very useful.

**Comment by smallhadroncollider** [comment]
I've written some truly horrifying nested code to fix this. It works, but it's grim. Release coming soon.

Definitely need to go back and refactor the API code at some point.

**Comment by smallhadroncollider** [comment]
Currently new lines in task descriptions lose newlines. I need to fix this, but before I do I need to fix rendering when there are newlines - which is not a simple task.

**Comment by smallhadroncollider** [comment]
[1.9.2](https://github.com/smallhadroncollider/taskell/releases/tag/1.9.2)

**Comment by Psykopear** [comment]
Great, thank you :)
