### ISSUE TITLE
Make it easier to know the keybindings

### ISSUE THREAD

**Issue by tylerlmz1** [smallhadroncollider/taskell#66]
I just found this software and really loved it

just now when I looked at the README.md and your official website, I can't find the keybindings to learn how to use it, I was left to figure out what you pressed in the demo GIF

I later found out I can learn the keybindings by looking at ~/.config/taskell/bindings.ini
but this is not obvious to a newcomer like me

It would help a newcomer by putting this information in your README.md

Thanks for this software!

**Comment by jthvai** [comment]
The location to find the keybindings is stated in [this section of README.md](https://github.com/smallhadroncollider/taskell#controls), which points towards [this file](https://github.com/smallhadroncollider/taskell/blob/master/templates/bindings.ini), containing the defaults.

**Comment by tylerlmz1** [comment]
Oh I see, my bad, thanks!

**Comment by smallhadroncollider** [comment]
Thanks @jthvai!

If you press `?` you'll get the list of key-bindings too (although there is currently a bug where you can't see the whole list if you've not got quite a tall terminal).
