### ISSUE TITLE
Can you compile taskell for ARM; i.e. Raspberry pi?

### ISSUE THREAD

**Issue by leeand00** [smallhadroncollider/taskell#75]
I see you have some x86/x64 builds for taskell, is there a way to either:

a. Compile it myself for Raspbian...
b. Make a .deb available for ARM / Raspbian?

I myself am not familar with Haskell (though I know other languages like Java, Node.js, etc)

**Comment by smallhadroncollider** [comment]
I think someone tried (although I can't find it anywhere) and didn't have any luck trying to run it on ARM. Not sure we worked out exactly what the issue was. Not 100% sure GHC supports ARM - can't find much information about it.

There's this: https://github.com/blitzcode/hue-dashboard/blob/master/README.md#raspberry-pi - doesn't look too hopeful.

**Comment by leeand00** [comment]
Bummer!  I really like your Kanban software; I guess I'll just have to connect to something else other than my pi to use it.

**Comment by leeand00** [comment]
Incidently; what is GHC?

**Comment by smallhadroncollider** [comment]
"Glasgow Haskell Compiler" - I forget why it's called that. A conference in Glasgow maybe?

**Comment by smallhadroncollider** [comment]
Started by someone in Glasgow University: https://en.wikipedia.org/wiki/Glasgow_Haskell_Compiler

**Comment by leeand00** [comment]
Can't you cross-compile it for ARM?

(Here's [a guy](https://svejcar.dev/posts/2019/09/23/haskell-on-raspberry-pi-4/) that tried to compile it on a Raspberry Pi4...but I would think that would be too slow)

Most of the time you can compile things for another platform (on another platform).

https://gitlab.haskell.org/ghc/ghc/-/wikis/cross-compilation

**Comment by leeand00** [comment]
The binary that is created is different, so you can compile something on an x86/x64 for an ARM processor; you won't be able to run it, until you get it on an ARM7 processor (or emulator, KVM / QEMU for instance) but the compiled binary will still run on the target architecture of the build.

**Comment by smallhadroncollider** [comment]
Quite possibly. By all means give it a go!

Unfortunately I barely have time to work on bugs at the moment, so I'm not going to get round to doing this myself. Let me know if you have any success.

**Comment by leeand00** [comment]
Okay, I'm waiting on a [reply](https://github.com/AlexeyRaga/ghc-docker-cross-arm/issues/2) from here since there appears to be a docker image for doing this, but as of yet I can't find it.  (Maybe because I need enterprise to get it or something, but well see).

**Comment by leeand00** [comment]
Hmm [this looks pretty good too](https://gitlab.haskell.org/ghc/ghc/-/wikis/building/cross-compiling-on-debian)...maybe I'll give it a try.

**Comment by smallhadroncollider** [comment]
Just seen this from last month: https://www.haskell.org/ghc/blog/20200515-ghc-on-arm.html
