### ISSUE TITLE
Ability to change default template

### ISSUE THREAD

**Issue by rrmelcer** [smallhadroncollider/taskell#76]
I don't know but is this a Issue. It is possible to create markdown files as templates for my kanban boards. It's more easy manage different project types in taskell, in my opinion.

**Comment by smallhadroncollider** [comment]
Do you mean creating a markdown file which is then used as the default for new projects with Taskell?

**Comment by rrmelcer** [comment]
Yes, that I mean.

**Comment by smallhadroncollider** [comment]
That sounds like a useful feature. I'll have a look into it when I get a bit of spare time (which I do not have much of at the moment).

**Comment by smallhadroncollider** [comment]
You'll be able to edit `~/.config/taskell/template.md` to change the default template from 1.10.0 onwards.
