### ISSUE TITLE
Show line where parsing failed

### ISSUE THREAD

**Issue by grepsuzette** [smallhadroncollider/taskell#77]
Would it be possible that whenever `taskell.md: Could not parse file.` is shown we also put a line number where it failed, to help fixing it?

I like to use both taskell and vim to edit my tasks but sometimes I introduce errors and then spend time to fix them. 

Good job at this super useful cli app!

**Comment by smallhadroncollider** [comment]
This is certainly something I'd like to get working. It actually used to do this, but then I changed to using a proper parsing engine (for future flexibility) and it got lost at that point. Would like to get it back, but will require a bit more understanding of attoparsec.

**Comment by smallhadroncollider** [comment]
Looks like this [might not be possible using attoparsec](https://www.reddit.com/r/haskell/comments/4ffjue/attoparsec_line_numbers/).

I'll have to think about this one. I chose attoparsec because it's used by other libraries that taskell is using.
