### ISSUE TITLE
When taskell.md ends with an empty line, parsing fails

### ISSUE THREAD

**Issue by emugel** [smallhadroncollider/taskell#78]
Or at least so it seems. 

The last issue #77 was actually solved when I removed the last empty line. Seems last line has to be not empty right now.

**Comment by smallhadroncollider** [comment]
Would not surprise me if that was the case. Was still trying to get my head around parsers when I wrote it, so probably some weird edge cases. Should be fairly easy to fix.

**Comment by smallhadroncollider** [comment]
Test added and failing.

**Comment by smallhadroncollider** [comment]
Will be fixed in the next release.
