### ISSUE TITLE
Copying existing list into Taskell

### ISSUE THREAD

**Issue by ThomWright** [smallhadroncollider/taskell#8]
I have an existing list of things I'd like to work through, where each item is on a new line, like so:

```
thing 1
thing 2
thing 3
...
```

Since there are 65 of them I didn't really want to manually write them all into Taskell, and copy/pasting put them all into a single item.

Any ideas how to easily get this list into Taskell?

**Comment by ThomWright** [comment]
I figured out I could just edit the markdown file! Case closed.

**Comment by smallhadroncollider** [comment]
Glad you worked it out.

I do want to add some importing options at some point.
