### ISSUE TITLE
Could not parse file

### ISSUE THREAD

**Issue by l4ur3ntc** [smallhadroncollider/taskell#85]
Hi,

I created a new taskell file and entered 2 tasks. For now, I don't understand how, but I reached this kind of situation while only using taskell (no manual edit of the file):

```
$ cat taskell.md 
## To Do

- task 1
    @ 2020-09-01
- task 2

    @ 2020-09-02

## Doing


## Done
```

The empty line before the due date gets taskell to fail parsing the file on the next run:
```
$ taskell
taskell.md: Could not parse file.
```

**Comment by smallhadroncollider** [comment]
Hmm. I'll see if I can work out how that happened. There aren't that many things that could cause a line-break before a date, so hopefully easy enough to track down.

**Comment by smallhadroncollider** [comment]
I think the only way this can happen is if a line break somehow gets into the task at the end. I managed to replicate it by copying a pasting a line break in manually – but it doesn't seem very likely that's what you did. I'll check the trim function removes line breaks too.

**Comment by smallhadroncollider** [comment]
Ok, I can't update the parser to read the broken file (it would be ambiguous), but hopefully I've got rid of the issue that caused it now.
