### ISSUE TITLE
Todo.txt file support

### ISSUE THREAD

**Issue by uGeek** [smallhadroncollider/taskell#87]
Great project, congratulations.

Are you planning to add support for todo.txt plaintext files?

**Comment by smallhadroncollider** [comment]
It looks like there are already CLI apps for Todo.txt, so not sure there's much point replicating them.

I'm not sure how the format would work with a Kanban board?

**Comment by uGeek** [comment]
There is a project that integrates the kanban board based on projects. I manage it like that and it is very comfortable

https://github.com/topydo/topydo

**Comment by smallhadroncollider** [comment]
Given there's already a CLI app that does it, I'm not sure it's something I'm going to get round to. There are already bits of functionality that taskell has that aren't part of Todo.txt and vice-versa.
