### ISSUE TITLE
Custom keyboard bindings

### ISSUE THREAD

**Issue by ThomWright** [smallhadroncollider/taskell#9]
My fingers don't know `hjkl`, they instinctively reach for the arrow keys. Any chance they could behave as I expect, in addition to the `hjkl` keys?

**Comment by smallhadroncollider** [comment]
I am planning on adding custom keyboard mapping at some point. Not sure I want to commit the arrow keys to the same functionality by default.

**Comment by ThomWright** [comment]
What would be the downside?

**Comment by smallhadroncollider** [comment]
It's possible at some point I'd like to add other features that the arrow keys might be useful for. If I double up their usage now then it'll be hard to back-pedal later. Having said that there's about fifty keys that all put you into edit mode...

For now you could edit the `Events.Actions.Normal` file and update the keybindings and then do a custom build 😉

**Comment by fosskers** [comment]
For Dvorak or Colemak users, `hjkl` is also a bit funky. For spacemacs, we have:
```lisp
     (keyboard-layout :variables kl-layout 'colemak-hnei)
```
As a quick setting we can do.

**Comment by smallhadroncollider** [comment]
This is definitely something I'd like to get added in soon.

**Comment by cvoges12** [comment]
I've been using my own hnei colemak format for a while with vim. I was about to write a fork with similar bindings for taskell. It might be a good idea to merge this as an optional feature.

**Comment by smallhadroncollider** [comment]
I will make this higher priority. Hadn't considered non-QWERTY keyboard layouts.

I won't merge in a branch if it *just* adds a different set of key-bindings. But if it adds the ability to change key-bindings with a preference file then I'd happily merge it. But that's probably quite a big rewrite.

**Comment by cvoges12** [comment]
The fork of mine is just a different set of key bindings because I have no intention of using qwerty. So yes, there would be no benefit of a merge. But any keys that would have had conflicting bindings have been worked out. Also, I have another person that can work out dvorak keybindings if you want. Besides the `?` aka `showHelp` function. It would be as easy as loading a separate colemak or dvorak version of the `Events.Actions.Normal.hs` based on a config.

**Comment by smallhadroncollider** [comment]
Thanks for the offer, but I'd prefer to put in full custom key-binding rather than catering for a few specific keyboard layouts. As I say, I'll make this higher priority than it had been.

**Comment by smallhadroncollider** [comment]
@ThomWright Here you go, once you've got 1.4.0 installed you can update navigation lines in the `bindings.ini`:

```
previous = <Up>
next = <Down>
left = <Left>
right = <Right>
```

There are a few issues that still need addressing: if a line is missing in the bindings file then there's no default and it doesn't currently check for missing bindings. But I'll work on those soon.
