### ISSUE TITLE
Unable to understand the keyboard shortcuts to shift task left/right to top of the list

### ISSUE THREAD

**Issue by yohannes** [smallhadroncollider/taskell#94]
I see in the help menu that these are the two characters for the shift functions aforementioned in the title: `˙ / ¬  `. But, I cant figure out what kind of characters they are on my keyboard. Can anyone help?

Best,
Yohannes

**Comment by smallhadroncollider** [comment]
There’s information about the keyboard bindings here: https://github.com/smallhadroncollider/taskell

Default bindings here: https://github.com/smallhadroncollider/taskell/blob/master/templates/bindings.ini

I think on Mac they’re Alt + H/J maybe? But you can change them to whatever you like.

**Comment by yohannes** [comment]
Well noted w. thanks. It's straight forward in hindsight.
