### ISSUE TITLE
Functionality to specify a path to a task file when opening Taskell

### ISSUE THREAD

**Issue by damienomurchu** [smallhadroncollider/taskell#95]
New to taskell, but it looks great (great job @smallhadroncollider !)

From what I see presently the config file only allows you to specify the name for a task file (which it will look for in the directory in which you open taskell). 

It would be great to have a commandline flag where you could specify the path to a task file to use. That way you could have global task boards that lived in a central location, as well open specific project boards without being in the directory in which they lived. 

I was wondering if there are any plans to add this functionality (or if I'm missing some undocumented flag) ?

**Comment by developmark** [comment]
Like most Unix apps, it supports any file path. You don’t have to be in the same directory:

`taskell -/spoons/peculiar/walruses.md`

Or am I misunderstanding the question?

**Comment by smallhadroncollider** [comment]
(Oops, was logged in on my work account)

**Comment by damienomurchu** [comment]
Tried that, but taskell appends `$HOME/` to the specified file path, ie

```
❯ taskell ~/scratch/new-board.md
Create /home/dm//home/dm/scratch/new-board.md? (Y/n): 
```

My config: 
```
❯ cat ~/.config/taskell/config.ini 
[general]
filename = taskell.md

[layout]
padding = 1
column_width = 30
column_padding = 3
description_indicator = "≡"
statusbar = true

[markdown]
title = "##"
task = "-"
summary = "    >"
due = "    @"
subtask = "    *"
localTimes = false
```

I probably need to learn me some haskell to dig around in the code :-)

**Comment by smallhadroncollider** [comment]
Hmm, ok, that sounds like a bug then. It certainly used to work!

**Comment by damienomurchu** [comment]
Actually, just a bug when specifying SHOME in the path, leaving it out it works ok:
```
❯ taskell scratch/new-board.md 
Create /home/dm/scratch/new-board.md? (Y/n):
```
```
❯ cat scratch/new-board.md 
## To Do


## Doing


## Done



```
Thanks for setting me on the right path :+1:

**Comment by smallhadroncollider** [comment]
Looks like the prompt adds the pwd on the front: https://github.com/smallhadroncollider/taskell/blob/ae915de8c4dd5d7d0b2c85277f1ab21e6b314b96/src/Taskell/IO.hs#L126

It won’t actually use that in the path it creates/loads. So it’s only the prompt that is broken - should actually do what you want.

Should be easy fix - just need to use the full path instead of appending the working directory. That was a very early bit of code - amazed it’s never come up before!

**Comment by damienomurchu** [comment]
Looks like it does use the `$HOME/`, its not just the prompt, fyi

```sh
~ took 30s 
❯ taskell scratch/test1.md  
Create /home/dm/scratch/test1.md? (Y/n): Y

~ took 6s 
❯ taskell ~/home/scratch/test2.md  
Create /home/dm//home/dm/home/scratch/test2.md? (Y/n): Y
taskell: /home/dm/home/scratch/test2.md: openBinaryFile: does not exist (No such file or directory)

~ took 2s 
❯ taskell ./scratch/test3.md  
Create /home/dm/./scratch/test3.md? (Y/n): Y

~ took 4s 
❯ ls ~/scratch | grep test   
test1.md
test3.md

```

**Comment by damienomurchu** [comment]
> https://github.com/smallhadroncollider/taskell/blob/ae915de8c4dd5d7d0b2c85277f1ab21e6b314b96/src/Taskell/IO.hs#L126
> 
> It won’t actually use that in the path it creates/loads. So it’s only the prompt that is broken - should actually do what you want.
> 
> Should be easy fix - just need to use the full path instead of appending the working directory. That was a very early bit of code - amazed it’s never come up before!

**Comment by smallhadroncollider** [comment]
(As mentioned in the PR #96) Looks like there's also  the same bug in the `createPath` function too. But should be a simple enough fix.

**Comment by smallhadroncollider** [comment]
Fixed in the next release
