### ISSUE TITLE
More options to add subtasks

### ISSUE THREAD

**Issue by gonced8** [smallhadroncollider/taskell#99]
When I try to add a subtask, I'm only able to do it with the "a" key, which adds a new subtask to the bottom. It would be useful to be able to use "o" and "O" to add a subtask below or above the current subtask (the same key bindings as for normal tasks).

**Comment by gonced8** [comment]
Nevermind, just saw this topic in your roadmap. Sorry...

**Comment by smallhadroncollider** [comment]
No worries. Yes, ideally I'd like to get the subtasks and tasks views using the same logic so they can share all the key bindings. Haven't had time to get onto this yet (in the last year I haven't had time to do much!)

**Comment by gonced8** [comment]
Don't worry, it's an amazing app nonetheless! I've been using it for the last couple of days and I'm enjoying it very much. Thank you for your work!

**Comment by smallhadroncollider** [comment]
This is in the latest release thanks to the hard work of @AliNisarAhmed. Enjoy!

**Comment by gonced8** [comment]
Nice! Thanks for the update!
